version: '2'

services:
  gauntlet-backend:
    build:
      context: ./images/backend
      dockerfile: Dockerfile
    ports:
     - "8080:8080"
    env_file:
     - common-db-vars.env
    links:
     - gauntlet-db:gaunt_db
    image: gauntlet-backend
  gauntlet-db:
    build:
      context: ./images/db
      dockerfile: Dockerfile
    image: gauntlet-db
    ports:
      - "5432:5432"
    volumes:
      - gauntlet-db-volume:/var/lib/postgresql/data
volumes:
  "gauntlet-db-volume":
    external: true